### ISSUE TITLE
Signature not valid: Incorrect Access key

### ISSUE THREAD

**Issue by PokerChang** [HuobiRDCenter/huobi_Python#119]
MacOS 11.5.1 . Tried Python version 3.6 and 3.9 and get the same error (virtualenv). And I tried many different pairs of keys and same error. The same keys work in a javascript library: https://github.com/airicyu/huobi-api-js

python example/account/get_balance.py

Traceback (most recent call last):
  File "example/account/get_balance.py", line 10, in <module>
    list_obj = account_client.get_balance(account_id=g_account_id)
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/client/account.py", line 41, in get_balance
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/service/account/get_balance.py", line 24, in request
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/restapi_sync_client.py", line 116, in request_process
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/restapi_sync_client.py", line 121, in request_process_product
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/impl/restapi_invoker.py", line 67, in call_sync
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/impl/restapi_invoker.py", line 30, in check_response
huobi.exception.huobi_api_exception.HuobiApiException: ('ExecuteError', '[Executing] api-signature-not-valid: Signature not valid: Incorrect Access key [Access key错误]')

**Comment by PokerChang** [comment]
Tried the same keys on Windows10 + Python 3.8 and get the same error.
