### ISSUE TITLE
TypeError: Only timezones from the pytz library are supported

### ISSUE THREAD

**Issue by dishu1** [HuobiRDCenter/huobi_Python#149]
Hi, I'm running the code below in a conda environment with python 3.11. I installed the library by doing git clone https://github.com/HuobiRDCenter/huobi_Python.git, cd into directory, pip install -r requirements.txt and pip install .

`from huobi.client.market import MarketClient
from huobi.model.market import *

def callback(obj_event: 'MarketDetailEvent'):
    obj_event.print_object()
    print()

market_client = MarketClient()
market_client.sub_market_detail("btcusdt", callback)`

And I get:
`Traceback (most recent call last):
  File "htx.py", line 11, in <module>
    market_client.sub_market_detail("btcusdt", callback)
  File "miniconda3/envs/htx/lib/python3.11/site-packages/huobi/client/market.py", line 273, in sub_market_detail
    from huobi.service.market.sub_market_detail import SubMarketDetailService
  File "miniconda3/envs/htx/lib/python3.11/site-packages/huobi/service/market/sub_market_detail.py", line 5, in <module>
    from huobi.connection.subscribe_client import SubscribeClient
  File "miniconda3/envs/htx/lib/python3.11/site-packages/huobi/connection/subscribe_client.py", line 9, in <module>
    class SubscribeClient(object):
  File "miniconda3/envs/htx/lib/python3.11/site-packages/huobi/connection/subscribe_client.py", line 11, in SubscribeClient
    subscribe_watch_dog = WebSocketWatchDog()
                          ^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/htx/lib/python3.11/site-packages/huobi/connection/impl/websocket_watchdog.py", line 42, in __init__
    self.scheduler.add_job(watch_dog_job, "interval", max_instances=10, seconds=1, args=[self])
  File "miniconda3/envs/htx/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/htx/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/htx/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/htx/lib/python3.11/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
                    ^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/htx/lib/python3.11/site-packages/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported`

I can't even guess because no examples seem to use the timezone in any way.

**Comment by kulakaka** [comment]
I've encountered the same issue

**Comment by kulakaka** [comment]
This issue is because of imcompatible of python veriosn changes. 
If you using python 3.11 ,  it will rasie some internal timezone handing. this issue occurs when apscheduler is installed with versions that are not fully compatible with Python 3.11.

Resolve this issue by add below

From:
        self.scheduler = BlockingScheduler()
To: 
        self.scheduler = BlockingScheduler(timezone=pytz.timezone("UTC"))

in huobi/connection/impl/websocket_watchdog.py
